version: '3'
services:
  database: 
    build: 
      context: ./sql
      dockerfile: Dockerfile
    container_name: hudex-database
    ports:
      - "13306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  hudex:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: hudex-service
    ports:
      - "3000:3000"