version: '3'
services:
  database: 
    build: 
      context: ./sql
      dockerfile: Dockerfile
    container_name: hudex-database
    ports:
      - "23306:23306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  hudex:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: hudex-service
    depends_on: 
      - database
    ports:
      - "3000:3000"
    links: 
      - database
    external_links: 
      - hudex-database
  ubuntu:
    image: "alpine"
    container_name: alpine_test
    depends_on: 
      - database